[dnf_critical]
cockpit-bridge
cockpit-files
cockpit-machines
cockpit-podman
cockpit-session-recording
docker-ce
docker-ce-cli
docker-compose-plugin
fuse
samba
samba-client
tailscale

[brew_cli]
bat
fastfetch
fd
fish
fzf
gh
git
ripgrep
zoxide

[nix_cli]
bun
cargo
dust
fping
ipinfo
lf
lolcat
lsd
micro
nodejs
nushell
oh-my-posh
scrcpy
speed-cloudflare-cli
speedtest-cli
tgpt
tree
wush

[flatpak_gui]
org.fkoehler.KTailctl
org.gnome.Extensions
